
truncate table test_docs.t_f_01692fa;
truncate table test_docs.t_f_0190180;
truncate table test_docs.t_f_1168c6f;
truncate table test_docs.t_f_11d6328;
truncate table test_docs.t_f_2130062;
truncate table test_docs.t_f_2149883;
truncate table test_docs.t_f_215b2e9;
truncate table test_docs.t_f_2190030;
truncate table test_docs.t_f_21e81a6;
truncate table test_docs.t_f_31b92ad;
truncate table test_docs.t_f_31dc56b;
truncate table test_docs.t_f_31f8f7c;
truncate table test_docs.t_f_31fc45f;
truncate table test_docs.t_f_41830e9;
truncate table test_docs.t_f_519145b;
truncate table test_docs.t_f_519e6cd;
truncate table test_docs.t_f_6117ead;
truncate table test_docs.t_f_6135ec8;
truncate table test_docs.t_f_61ae463;
truncate table test_docs.t_f_61fcfd3;
truncate table test_docs.t_f_715a73f;
truncate table test_docs.t_f_81eed8d;
truncate table test_docs.t_f_a1cd4ff;
truncate table test_docs.t_f_b12e0d5;
truncate table test_docs.t_f_b1a3034;
truncate table test_docs.t_f_c11a6ab;
truncate table test_docs.t_f_c13b7f0;
truncate table test_docs.t_f_c19311b;
truncate table test_docs.t_f_c1bcdf1;
truncate table test_docs.t_f_d1107e3;
truncate table test_docs.t_f_d1193e2;
truncate table test_docs.t_f_d151227;
truncate table test_docs.t_f_d180879;
truncate table test_docs.t_f_d1970ba;
truncate table test_docs.t_f_d1c5f7d;
truncate table test_docs.t_f_e158ee0;
truncate table test_docs.t_f_f130ae4;
truncate table test_docs.t_f_f1d8b64;
truncate table test_docs.t_sign_fields;
truncate table test_docs.d_doc_lang;
truncate table test_docs.t_child_list;
truncate table test_docs.t_decision;
truncate table test_docs.t_e_sign;
truncate table test_docs.t_structure cascade ;
truncate table test_docs.t_document_body cascade;
truncate table test_docs.t_document_root cascade;
